const savedMaze = {
  totalRows: 20,
  totalColumns: 20,
  grid: [
    [
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: true },
    ],
    [
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
    ],
    [
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: false },
    ],
    [
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
    ],
    [
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: false },
    ],
    [
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: false },
    ],
    [
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: true, t: false },
    ],
    [
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
    ],
    [
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: true },
    ],
    [
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
    ],
    [
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: false },
    ],
    [
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: true },
    ],
    [
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: false, t: false },
    ],
    [
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
    ],
    [
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
    ],
    [
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: true },
    ],
    [
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: false },
      { l: true, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: false },
    ],
    [
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
    ],
    [
      { l: true, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: false },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: true },
      { l: true, r: true, b: false, t: false },
      { l: true, r: false, b: false, t: true },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: false, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: false, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: false, t: false },
    ],
    [
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: false },
      { l: true, r: false, b: true, t: true },
      { l: false, r: false, b: true, t: false },
      { l: false, r: false, b: true, t: true },
      { l: false, r: true, b: true, t: true },
      { l: true, r: true, b: true, t: false },
    ],
  ],
};
